name: deploy
on:
  push:
    # close だと手動でクローズした場合も実行されてしまう
    # types: [closed]
    # branches:
      # - release-prod
jobs:
  Deproy:
    # if分岐で制御
    # if: github.event.pull_request.merged == true
    # environment: production
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - run: echo "Hello Selfhosted Runner !!!"